//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define __LOADER__

#include "navigation.c"
#include "initialHeading.c"
#include "bluetooth.c"

#define RedBALLMIN 28
#define BlueBALLMAX 20


//global variables
int ballnumber=0; //ballno
int startLoader=2;//when 1 is sent from the master, CaptureBall is called, at the end, startLoader is set back to C


void RotateMotorEx(short motorX, int speed, unsigned int degrees){
  nMotorEncoderTarget[motorx]=degrees;
  motor[motorX]=speed;


  while(nMotorRunState[motorX]!= runStateIdle);
  //	bFloatDuringInactiveMotorPWM = false;


}



//////////////
//Puts the ball inside the mill thingy
////////////////////

void initprepBall(int ballno) {

  if(ballno != 3) {

    RotateMotorEx(motorC, 30, 90);
    wait1Msec(1500);
  }

}


//Checks that the ball has indeed been loaded
bool prepBall(){

  RotateMotorEx(motorC, -15, 50);

  wait1Msec(2000);

  if(SensorValue[ballSensor] >= BALLMIN){
    RotateMotorEx(motorC, 15, 50);
    return true;
  }

  else
  {
    RotateMotorEx(motorC, 15, 50);
    return false;
  }
}





/////////////////
//LOAD FUNCTION
//////////////

void Loader(){

  //  i is a counter that is incremented each time the loader function is called, by the ball detection code */

  if (ballnumber<4) {
    ballnumber++;

    switch(ballnumber)
    {

    case 1: // load the first ball
      {

        //Wait(1000);  // loader waits 1 second

        RotateMotorEx(motorC,30,360);
        wait1Msec(200);
        return;

      }

    case 2:
      {
        //wait1Msec(1000);  // loader wait1Msecs 1 second

        RotateMotorEx(motorC,40,360);
        wait1Msec(150);
        return;

      }

    case 3:
      {

        //wait1Msec(1000);  // loader wait1Msecs 1 second

        RotateMotorEx(motorC,30,110);
        wait1Msec(100);
        return;
      }

    }
}}



//////////////////////////////////////
//unload function.
/////////////////////////////////

void unload(int ballno){

  initprepBall(ballno);

  while(!prepBall()){
    prepBall();    //prepball to put ball in correct location
  }

  wait1Msec(2000);

  RotateMotorEx(motorC, -30, 90);   //eject

  ballnumber--;

  wait1Msec(500);
  //lowerEff();
  return;
}





void captureBall(){


  while(true){
    if(SensorValue[S4] >= RedBALLMIN || SensorValue[S4]<BlueBALLMAX){
      Loader();

      //Change variable to notify capture
      break;}

  }
  startLoader=2;

}




task main(){
InitialPosition();


int xCup=0, yCup=0, ThetaCup=0;


//int arrived = NOT_ARRIVED;


while (true){
	while (ballnumber < 3 ){ //|| (TimeSpent < 5)
		int result;
		result = navigate(x,y, false, true, 1);

		if (result == ARRIVED_AT_TARGET){
			//SelectNextWaipoint(global array of waypoints);
		}
		else //(result == FOUND_BALL)
		{
			//findBallHeading();
			//FindBallDistance();
			Loader();
		}
	}

	navigate(xCup, yCup, true, true, 1);

	//At this point we should have 3 balls or be late

	while(ballnumber !=0){

	btsend(GOTOCUP,0,0);

	while(!CONFIRMATION) //Wait until it gets here
		wait1Msec(1);

	btsend(LOWER_SCOOP,0 , 0);

	while(!CONFIRMATION) //Wait until it gets here
		wait1Msec(1);


	//CHANGE HERE THE NUMBER OF BALLS TO BE DUMPED!!!


	unload(ballnumber); //1 or three balls??

	btsend(LIFT_SCOOP,0,0);

	while(!CONFIRMATION) //Wait until it gets here
		wait1Msec(1);

	btsend(UNLOAD_BALLS,0,0);

	while(!CONFIRMATION) //Wait until it gets here
		wait1Msec(1);

	btsend(GO_TO_WAITING_STATE,0,0); //wherever the hell that is

	while(!CONFIRMATION) //Wait until it gets here
		wait1Msec(1);}


}
}
