
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "bt.c"

#define BALLMIN 25


//global variables
int ballnumber=2; //ballno
int startLoader=2;//when 1 is sent from the master, CaptureBall is called, at the end, startLoader is set back to C

void RotateMotor(short motorX, int speed, unsigned int degrees){
  nMotorEncoderTarget[motorx]=degrees;
  motor[motorX]=speed;


  while(nMotorRunState[motorX]!= runStateIdle);
  //	bFloatDuringInactiveMotorPWM = false;


}



//////////////
//Puts the ball inside the mill thingy
////////////////////

void initprepBall(int ballno) {

  if(ballno != 3) {

    RotateMotor(motorC, 30, 90);
    wait1Msec(1500);
  }

}


//Checks that the ball has indeed been loaded
bool prepBall(){

  RotateMotor(motorC, -15, 50);

  wait1Msec(2000);

  if(SensorValue(S1) >= BALLMIN){
    RotateMotor(motorC, 15, 50);
    return true;
  }

  else
  {
    RotateMotor(motorC, 15, 50);
    return false;
  }
}



//LOWER THE END EFFECTOR

void lowerEff(){

  RotateMotor(motorA, 30, 118);

}


void raiseEff(){
  RotateMotor(motorA,-30, 118);
}



void syncRaise(){
  wait1Msec(1000);
  RotateMotor(motorA,-60, 110);

}

/////////////////
//LOAD FUNCTION
//////////////

void Loader(){

  //  i is a counter that is incremented each time the loader function is called, by the ball detection code */

  if (ballnumber<4) {
    ballnumber++;

    switch(ballnumber)
    {

    case 1: // load the first ball
      {

        //Wait(1000);  // loader waits 1 second

        RotateMotor(motorC,30,360);
        wait1Msec(200);
        return;

      }

    case 2:
      {
        //wait1Msec(1000);  // loader wait1Msecs 1 second

        RotateMotor(motorC,40,360);
        wait1Msec(150);
        return;

      }

    case 3:
      {

        //wait1Msec(1000);  // loader wait1Msecs 1 second

        RotateMotor(motorC,30,110);
        wait1Msec(100);
        return;
      }

    }
}}



//////////////////////////////////////
//unload function.
/////////////////////////////////

void unload(int ballno){

  initprepBall(ballno);

  while(!prepBall()){
    prepBall();    //prepball to put ball in correct location
  }

  wait1Msec(2000);

  RotateMotor(motorC, -30, 90);   //eject

  ballnumber--;

  wait1Msec(500);
  //lowerEff();
  return;
}





void captureBall(){


  while(true){
    if(SensorValue[S4] >= BALLMIN){
      Loader();

      //Change variable to notify capture
      break;}

  }
  startLoader=2;

}

//booleans for capture ball
bool captureBallBool=false;
bool stopCapture=false;

//boolean for rendez-vous
bool maximumBall=false;

//booleans for lifting
bool liftEff=false;
bool liftDone=false;

//booleans for unloading
bool unloadBall = false;
bool unloadDone = false;

void prepareDataToSend() {
    //Process data before sending
    if(stopCapture) {
      stopCapture=false;
      dataToSend[1] =2;
    }

    if(maximumBall){
      dataToSend[2] = 1;}

    if(liftDone){
      liftDone=false;
      dataToSend[4] =1;
    }

    if(unloadDone){
      unloadDone=false;
      dataToSend[6] = 1;
      nxtDisplayCenteredTextLine(4, "zzzzzz");
    }
}

task communication()
{
  while(true) {
    wait1Msec(50);

    readAndSend(mailbox1, mailbox11);
    nxtDisplayCenteredTextLine(4, "asdasd");

    //process data received
    captureBallBool=(dataReceived[1]==1);
    liftEff=(dataReceived[3]==1);
    unloadBall=(dataReceived[5]==1);

    wait1Msec(100);nxtDisplayCenteredTextLine(4, "asdasd4");
    clearBTMessage();
  }
}

task main{
  checkBTLinkConnected();
  cCmdBTPurgeRcvBuffer();
  purgeBT(mailbox1);
  wait1Msec(500);
  SensorType[S4] = sensorLightActive;
  SensorMode[S4] = modePercentage;

  StartTask(communication);

  while(true){
    if(captureBallBool){
      captureBallBool=false;
      captureBall();
      stopCapture=true;
    }

    if(ballnumber==3){
      maximumBall = true;
    }

    if(unloadBall){
      unloadBall=false;
      unload(ballnumber);
      nxtDisplayCenteredTextLine(3, "asdasd");
      unloadDone=true;
    }

    if(liftEff){
      liftEff=false;
      syncRaise();
      liftDone=true;
    }
  }
}
