#pragma config(Sensor, S1,     ranaWantsMeOn,       sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
int first = 0;
ubyte dataToSend[3] = {1,2,3};
while (true){



  wait1Msec(400);  // Don’t send messages too frequently.
  //if (first){
  /*  cCmdMessageWriteToBluetooth(1, dataToSend, 3, mailbox1);
        wait1Msec(400);
    sendMessageWithParm(SensorValue[S1],0, 0);
    first = 1;
 // }
 //  else
 //  {
    cCmdMessageWriteToBluetooth(2, dataToSend, 3, mailbox2);
        wait1Msec(400);*/
//    sendMessageWithParm(SensorValue[S1],SensorValue[S1], 0);
   // wait10Msec(20);
    //

     sendMessageWithParm(SensorValue[S1],SensorValue[S1], 0);
	   first = nBTCurrentStreamIndex;
     cCmdMessageWriteToBluetooth(2, dataToSend, 3, mailbox1);
	   first = nBTCurrentStreamIndex;
     wait10Msec(20);


     while (true){
	     sendMessageWithParm(SensorValue[S1],SensorValue[S1], 0);
	     cCmdMessageWriteToBluetooth(2, dataToSend, 3, mailbox1);
	     wait10Msec(5);
	   }


	   first = nBTCurrentStreamIndex;
     cCmdMessageWriteToBluetooth(1, dataToSend, 3, mailbox1);
     first = nBTCurrentStreamIndex;
     wait10Msec(20);


   // wait10Msec(20);
    //


//    first = 0;
 // }


/*    cCmdMessageWriteToBluetooth(nStream, pData, nLength, nQueueID);
Writes a Bluetooth message to 'nQueueID'. The message will be written to the specified 'port' or
'nStream' which should be in the range of 0 to 3.
This command is only useful when multiple ports are simultaneously open on the NXT;
a configuration that is not recommended because of the much slower communications when multiple
ports are in use. The message data is taken from the buffer at 'pData'.
'nLength' is the number of bytes in the message; the maximum length is 58 bytes.

*/
}
}
