#pragma config(Sensor, S1,     ,                    sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//might need an IfDef?? Im not sure
//#include// "navigation.c"

//Similar to the RotateMotor Function in NXC, used for the Loader and Scooper Motor
//THINGS TO CHECK ASAP:argument "string motorX", right or wrong
//						1. If used to rotate BACKWARDS, does it cause a problem?
//						2. Is nMotorEncoder[motorX] in Degrees????
void RotateMotor(short motorX, int speed, unsigned int degrees){
	nMotorEncoderTarget[motorx]=degrees;
	motor[motorX]=speed;


	while(nMotorRunState[motorX]!= runStateIdle);
	//	bFloatDuringInactiveMotorPWM = false;

	/*

	nMotorEncoder[motorX] = 0;
	while(nMotorEncoder[motorX] < degrees ) {
	motor[motorX] = speed;
	}
	motor[motorX] = 0;
	*/
}
/////
//BALLMIN HAVE TO BE DEFINED As THE CONSTANTS FOR BLUE AND RED BALLS. 25 is placeholder value
#define BALLMIN 25

//////////////
//Puts the ball inside the mill thingy
////////////////////

void initprepBall(int ballno){

	if(ballno != 1){

		RotateMotor(motorC, 30, 90);
		wait1Msec(1500);}

}


//Checks that the ball has indeed been loaded
bool prepBall(){

	RotateMotor(motorC, -20, 50);

	wait1Msec(2000);

	if(SensorValue(S1) >= BALLMIN){
		RotateMotor(motorC, 20, 50);
		return true;}

	else
	{RotateMotor(motorC, 20, 50);
		return false;
	}
}



//LOWER THE END EFFECTOR

void lowerEff(){

	RotateMotor(motorA, 30, 118);
	RotateMotor(motorA,-30, 118);
}



//////////////////////////////////////
//unload function.
/////////////////////////////////

void unload(int ballno){

	initprepBall(ballno);

	do{
		prepBall();    //prepball to put ball in correct location
	}while(!prepBall());

	wait1Msec(1500);

	RotateMotor(motorC, -30, 90);   //eject

	wait1Msec(1500);
	lowerEff();
}


//for testing
//should be working properly now
task main()
{



	//test cases: unload(1) for ball#3, unload(2&3) for balls 2 and 3
	///////////////////////
	unload(1);
	wait1Msec(1000);
	unload(2);
	wait1Msec(1000);
	unload(3);
}
